/**
 * Catalogue de produits par défaut (presets hors miel) — semés en base au
 * premier accès de l'utilisateur (estDefaut=true) pour qu'ils soient éditables.
 * `categorie` = enum categorie_stock ; `categorieVente` = enum categorie_vente.
 */
export interface PresetDefaut {
  nom: string;
  categorie: string;
  categorieVente: string | null;
  tauxTva: number | null;
  uniteTypique: string;
  modePrix: 'format' | 'poids';
  icon: string;
  groupe: string;
}

export const CATALOGUE_DEFAUT: PresetDefaut[] = [
  // ── Produits de la ruche (5,5 %)
  {
    nom: 'Pollen frais',
    categorie: 'conditionnement',
    categorieVente: 'pollen',
    tauxTva: 5.5,
    uniteTypique: 'pots',
    modePrix: 'format',
    icon: '🌼',
    groupe: 'Produits de la ruche',
  },
  {
    nom: 'Pollen sec',
    categorie: 'conditionnement',
    categorieVente: 'pollen',
    tauxTva: 5.5,
    uniteTypique: 'pots',
    modePrix: 'format',
    icon: '🌾',
    groupe: 'Produits de la ruche',
  },
  {
    nom: 'Propolis brute',
    categorie: 'conditionnement',
    categorieVente: 'propolis_alimentaire',
    tauxTva: 5.5,
    uniteTypique: 'g',
    modePrix: 'poids',
    icon: '🟤',
    groupe: 'Produits de la ruche',
  },
  {
    nom: 'Gelée royale',
    categorie: 'conditionnement',
    categorieVente: 'gelee_royale',
    tauxTva: 5.5,
    uniteTypique: 'pots',
    modePrix: 'format',
    icon: '👑',
    groupe: 'Produits de la ruche',
  },
  {
    nom: "Pain d'abeille",
    categorie: 'conditionnement',
    categorieVente: 'pain_abeille',
    tauxTva: 5.5,
    uniteTypique: 'pots',
    modePrix: 'format',
    icon: '🍯',
    groupe: 'Produits de la ruche',
  },
  {
    nom: 'Cire en bloc',
    categorie: 'conditionnement',
    categorieVente: 'cire_alimentaire',
    tauxTva: 5.5,
    uniteTypique: 'kg',
    modePrix: 'poids',
    icon: '🟡',
    groupe: 'Produits de la ruche',
  },

  // ── Produits transformés (20 %)
  {
    nom: 'Propolis (teinture)',
    categorie: 'conditionnement',
    categorieVente: 'propolis_teinture',
    tauxTva: 20,
    uniteTypique: 'flacons',
    modePrix: 'format',
    icon: '🧪',
    groupe: 'Produits transformés',
  },
  {
    nom: 'Hydromel',
    categorie: 'conditionnement',
    categorieVente: 'hydromel',
    tauxTva: 20,
    uniteTypique: 'bouteilles',
    modePrix: 'format',
    icon: '🍶',
    groupe: 'Produits transformés',
  },
  {
    nom: 'Baume / cosmétique',
    categorie: 'conditionnement',
    categorieVente: 'cosmetique',
    tauxTva: 20,
    uniteTypique: 'pots',
    modePrix: 'format',
    icon: '🧴',
    groupe: 'Produits transformés',
  },
  {
    nom: 'Savon au miel',
    categorie: 'conditionnement',
    categorieVente: 'cosmetique',
    tauxTva: 20,
    uniteTypique: 'pièces',
    modePrix: 'format',
    icon: '🧼',
    groupe: 'Produits transformés',
  },
  {
    nom: 'Bougie en cire',
    categorie: 'conditionnement',
    categorieVente: 'cire_technique',
    tauxTva: 20,
    uniteTypique: 'pièces',
    modePrix: 'format',
    icon: '🕯️',
    groupe: 'Produits transformés',
  },

  // ── Nourrissement (5,5 %)
  {
    nom: 'Sirop de nourrissement',
    categorie: 'nourrissement',
    categorieVente: 'nourrissement',
    tauxTva: 5.5,
    uniteTypique: 'L',
    modePrix: 'format',
    icon: '🥤',
    groupe: 'Nourrissement',
  },
  {
    nom: 'Candi / pâte',
    categorie: 'nourrissement',
    categorieVente: 'nourrissement',
    tauxTva: 5.5,
    uniteTypique: 'kg',
    modePrix: 'poids',
    icon: '🍬',
    groupe: 'Nourrissement',
  },
  {
    nom: 'Pâte protéinée',
    categorie: 'nourrissement',
    categorieVente: 'nourrissement',
    tauxTva: 5.5,
    uniteTypique: 'kg',
    modePrix: 'poids',
    icon: '🥮',
    groupe: 'Nourrissement',
  },

  // ── Traitements varroa (10 %)
  {
    nom: 'Apivar (amitraze)',
    categorie: 'traitement',
    categorieVente: 'traitement_veterinaire',
    tauxTva: 10,
    uniteTypique: 'lanières',
    modePrix: 'format',
    icon: '🛡️',
    groupe: 'Traitements',
  },
  {
    nom: 'Apibioxal',
    categorie: 'traitement',
    categorieVente: 'traitement_veterinaire',
    tauxTva: 10,
    uniteTypique: 'sachets',
    modePrix: 'format',
    icon: '🧫',
    groupe: 'Traitements',
  },
  {
    nom: 'Acide oxalique',
    categorie: 'traitement',
    categorieVente: 'traitement_veterinaire',
    tauxTva: 10,
    uniteTypique: 'g',
    modePrix: 'poids',
    icon: '⚗️',
    groupe: 'Traitements',
  },
  {
    nom: 'Acide formique (MAQS)',
    categorie: 'traitement',
    categorieVente: 'traitement_veterinaire',
    tauxTva: 10,
    uniteTypique: 'doses',
    modePrix: 'format',
    icon: '💧',
    groupe: 'Traitements',
  },

  // ── Ruches & cadres (20 %)
  {
    nom: 'Cadre filé',
    categorie: 'cadres',
    categorieVente: 'materiel_apicole',
    tauxTva: 20,
    uniteTypique: 'cadres',
    modePrix: 'format',
    icon: '🔲',
    groupe: 'Ruches & cadres',
  },
  {
    nom: 'Cadre gaufré',
    categorie: 'cadres',
    categorieVente: 'materiel_apicole',
    tauxTva: 20,
    uniteTypique: 'cadres',
    modePrix: 'format',
    icon: '🔳',
    groupe: 'Ruches & cadres',
  },
  {
    nom: 'Cire gaufrée (feuille)',
    categorie: 'cadres',
    categorieVente: 'cire_technique',
    tauxTva: 20,
    uniteTypique: 'feuilles',
    modePrix: 'format',
    icon: '📄',
    groupe: 'Ruches & cadres',
  },
  {
    nom: 'Hausse',
    categorie: 'hausses',
    categorieVente: 'materiel_apicole',
    tauxTva: 20,
    uniteTypique: 'hausses',
    modePrix: 'format',
    icon: '📦',
    groupe: 'Ruches & cadres',
  },
  {
    nom: 'Corps de ruche',
    categorie: 'corps',
    categorieVente: 'materiel_apicole',
    tauxTva: 20,
    uniteTypique: 'corps',
    modePrix: 'format',
    icon: '🟫',
    groupe: 'Ruches & cadres',
  },
  {
    nom: 'Toit',
    categorie: 'equipement',
    categorieVente: 'materiel_apicole',
    tauxTva: 20,
    uniteTypique: 'pièces',
    modePrix: 'format',
    icon: '🏠',
    groupe: 'Ruches & cadres',
  },
  {
    nom: 'Plancher / fond',
    categorie: 'equipement',
    categorieVente: 'materiel_apicole',
    tauxTva: 20,
    uniteTypique: 'pièces',
    modePrix: 'format',
    icon: '🪵',
    groupe: 'Ruches & cadres',
  },
  {
    nom: 'Nourrisseur',
    categorie: 'equipement',
    categorieVente: 'materiel_apicole',
    tauxTva: 20,
    uniteTypique: 'pièces',
    modePrix: 'format',
    icon: '🍽️',
    groupe: 'Ruches & cadres',
  },

  // ── Conditionnement (20 %)
  {
    nom: 'Pot verre 250 g',
    categorie: 'conditionnement',
    categorieVente: 'conditionnement',
    tauxTva: 20,
    uniteTypique: 'pots',
    modePrix: 'format',
    icon: '🫙',
    groupe: 'Conditionnement',
  },
  {
    nom: 'Pot verre 500 g',
    categorie: 'conditionnement',
    categorieVente: 'conditionnement',
    tauxTva: 20,
    uniteTypique: 'pots',
    modePrix: 'format',
    icon: '🫙',
    groupe: 'Conditionnement',
  },
  {
    nom: 'Pot verre 1 kg',
    categorie: 'conditionnement',
    categorieVente: 'conditionnement',
    tauxTva: 20,
    uniteTypique: 'pots',
    modePrix: 'format',
    icon: '🫙',
    groupe: 'Conditionnement',
  },
  {
    nom: 'Couvercle / capsule',
    categorie: 'conditionnement',
    categorieVente: 'conditionnement',
    tauxTva: 20,
    uniteTypique: 'pièces',
    modePrix: 'format',
    icon: '⚪',
    groupe: 'Conditionnement',
  },
  {
    nom: 'Étiquettes',
    categorie: 'conditionnement',
    categorieVente: 'conditionnement',
    tauxTva: 20,
    uniteTypique: 'pièces',
    modePrix: 'format',
    icon: '🏷️',
    groupe: 'Conditionnement',
  },

  // ── Outillage & équipement (20 %)
  {
    nom: 'Lève-cadre',
    categorie: 'outillage',
    categorieVente: 'equipement_apiculteur',
    tauxTva: 20,
    uniteTypique: 'pièces',
    modePrix: 'format',
    icon: '🪝',
    groupe: 'Outillage & équipement',
  },
  {
    nom: 'Enfumoir',
    categorie: 'outillage',
    categorieVente: 'equipement_apiculteur',
    tauxTva: 20,
    uniteTypique: 'pièces',
    modePrix: 'format',
    icon: '💨',
    groupe: 'Outillage & équipement',
  },
  {
    nom: 'Combinaison / vareuse',
    categorie: 'equipement',
    categorieVente: 'equipement_apiculteur',
    tauxTva: 20,
    uniteTypique: 'pièces',
    modePrix: 'format',
    icon: '🦺',
    groupe: 'Outillage & équipement',
  },
  {
    nom: 'Gants',
    categorie: 'equipement',
    categorieVente: 'equipement_apiculteur',
    tauxTva: 20,
    uniteTypique: 'paires',
    modePrix: 'format',
    icon: '🧤',
    groupe: 'Outillage & équipement',
  },
];
